-- Seed data for Finance Tracker

-- Insert Users
INSERT INTO users (id, name, email, password, role) VALUES (1, 'Admin User', 'admin@demo.com', '$2a$10$fQ0PS.LzguRtCHzS3j3MTuREvgMWQXVVNKUrrlIMK9Zk1BqurztKW', 'admin') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO users (id, name, email, password, role) VALUES (2, 'Regular User', 'user@demo.com', '$2a$10$fQ0PS.LzguRtCHzS3j3MTuREvgMWQXVVNKUrrlIMK9Zk1BqurztKW', 'user') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO users (id, name, email, password, role) VALUES (3, 'Read Only User', 'readonly@demo.com', '$2a$10$fQ0PS.LzguRtCHzS3j3MTuREvgMWQXVVNKUrrlIMK9Zk1BqurztKW', 'read-only') ON DUPLICATE KEY UPDATE id=id;

-- Insert Transactions
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 5000, 8, 'Monthly salary', '2026-05-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 1200, 9, 'Website project', '2026-05-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 800, 9, 'Logo design work', '2026-04-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 5000, 8, 'Monthly salary', '2026-04-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 300, 10, 'Stock dividends', '2026-04-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 5000, 8, 'Monthly salary', '2026-03-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 1500, 9, 'App development', '2026-03-04');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 5000, 8, 'Monthly salary', '2026-02-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 500, 10, 'Mutual fund returns', '2026-02-07');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 5000, 8, 'Monthly salary', '2026-01-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'income', 2000, 9, 'Consulting gig', '2025-12-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 250, 1, 'Grocery shopping', '2026-05-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 45, 2, 'Uber rides', '2026-05-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 120, 3, 'Concert tickets', '2026-05-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 89, 4, 'New headphones', '2026-05-10');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 150, 5, 'Electricity bill', '2026-05-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 200, 6, 'Gym membership', '2026-05-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 350, 7, 'Online course', '2026-04-28');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 180, 1, 'Restaurant dinner', '2026-04-26');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 60, 2, 'Gas refill', '2026-04-20');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 300, 4, 'Clothes shopping', '2026-04-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 75, 3, 'Movie night', '2026-04-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 130, 5, 'Internet bill', '2026-04-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 220, 1, 'Weekly groceries', '2026-03-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 95, 6, 'Doctor visit', '2026-03-24');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 500, 7, 'Textbooks', '2026-03-14');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 170, 1, 'Groceries', '2026-03-09');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 80, 2, 'Bus pass', '2026-02-27');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 200, 3, 'Gaming subscription', '2026-02-22');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 450, 4, 'Electronics', '2026-02-12');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 160, 5, 'Phone bill', '2026-02-02');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 280, 1, 'Dining out', '2026-01-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 100, 6, 'Pharmacy', '2026-01-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 55, 2, 'Parking fees', '2026-01-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (1, 'expense', 190, 1, 'Grocery run', '2025-12-24');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 5000, 8, 'Monthly salary', '2026-05-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 1200, 9, 'Website project', '2026-05-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 800, 9, 'Logo design work', '2026-04-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 5000, 8, 'Monthly salary', '2026-04-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 300, 10, 'Stock dividends', '2026-04-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 5000, 8, 'Monthly salary', '2026-03-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 1500, 9, 'App development', '2026-03-04');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 5000, 8, 'Monthly salary', '2026-02-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 500, 10, 'Mutual fund returns', '2026-02-07');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 5000, 8, 'Monthly salary', '2026-01-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'income', 2000, 9, 'Consulting gig', '2025-12-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 250, 1, 'Grocery shopping', '2026-05-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 45, 2, 'Uber rides', '2026-05-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 120, 3, 'Concert tickets', '2026-05-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 89, 4, 'New headphones', '2026-05-10');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 150, 5, 'Electricity bill', '2026-05-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 200, 6, 'Gym membership', '2026-05-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 350, 7, 'Online course', '2026-04-28');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 180, 1, 'Restaurant dinner', '2026-04-26');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 60, 2, 'Gas refill', '2026-04-20');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 300, 4, 'Clothes shopping', '2026-04-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 75, 3, 'Movie night', '2026-04-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 130, 5, 'Internet bill', '2026-04-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 220, 1, 'Weekly groceries', '2026-03-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 95, 6, 'Doctor visit', '2026-03-24');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 500, 7, 'Textbooks', '2026-03-14');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 170, 1, 'Groceries', '2026-03-09');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 80, 2, 'Bus pass', '2026-02-27');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 200, 3, 'Gaming subscription', '2026-02-22');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 450, 4, 'Electronics', '2026-02-12');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 160, 5, 'Phone bill', '2026-02-02');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 280, 1, 'Dining out', '2026-01-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 100, 6, 'Pharmacy', '2026-01-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 55, 2, 'Parking fees', '2026-01-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (2, 'expense', 190, 1, 'Grocery run', '2025-12-24');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 5000, 8, 'Monthly salary', '2026-05-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 1200, 9, 'Website project', '2026-05-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 800, 9, 'Logo design work', '2026-04-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 5000, 8, 'Monthly salary', '2026-04-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 300, 10, 'Stock dividends', '2026-04-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 5000, 8, 'Monthly salary', '2026-03-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 1500, 9, 'App development', '2026-03-04');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 5000, 8, 'Monthly salary', '2026-02-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 500, 10, 'Mutual fund returns', '2026-02-07');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 5000, 8, 'Monthly salary', '2026-01-16');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'income', 2000, 9, 'Consulting gig', '2025-12-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 250, 1, 'Grocery shopping', '2026-05-17');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 45, 2, 'Uber rides', '2026-05-15');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 120, 3, 'Concert tickets', '2026-05-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 89, 4, 'New headphones', '2026-05-10');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 150, 5, 'Electricity bill', '2026-05-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 200, 6, 'Gym membership', '2026-05-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 350, 7, 'Online course', '2026-04-28');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 180, 1, 'Restaurant dinner', '2026-04-26');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 60, 2, 'Gas refill', '2026-04-20');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 300, 4, 'Clothes shopping', '2026-04-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 75, 3, 'Movie night', '2026-04-08');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 130, 5, 'Internet bill', '2026-04-06');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 220, 1, 'Weekly groceries', '2026-03-29');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 95, 6, 'Doctor visit', '2026-03-24');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 500, 7, 'Textbooks', '2026-03-14');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 170, 1, 'Groceries', '2026-03-09');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 80, 2, 'Bus pass', '2026-02-27');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 200, 3, 'Gaming subscription', '2026-02-22');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 450, 4, 'Electronics', '2026-02-12');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 160, 5, 'Phone bill', '2026-02-02');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 280, 1, 'Dining out', '2026-01-23');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 100, 6, 'Pharmacy', '2026-01-13');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 55, 2, 'Parking fees', '2026-01-03');
INSERT INTO transactions (user_id, type, amount, category_id, description, date) VALUES (3, 'expense', 190, 1, 'Grocery run', '2025-12-24');
